eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  doctor-service:
    endpoints:
      endpoint:
        uri: http://DOCTOR-SERVICE/getAll/doctor-record
      endpoint:
        uri: http://DOCTOR-SERVICE/getAll/doctor-patient-records
  patient-service:
    endpoints:
      endpoint:
        uri: http://PATIENT-SERVICE/getAll/patient-record
